#!/usr/bin/env bash
#writes a Bash script that transfers a file from our client to a server

args_no=$#

if [ "$args_no" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
