#!/usr/bin/env bash
#installing nginx in the server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" >  /var/www/html/index.html
sudo service nginx restart
