#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”

if ! [ -x "$(command -v nginx)" ]; then
  apt-get update
  apt-get install -y nginx
fi

echo 'Hello World!' > /var/www/html/index.html
SERVER_BLOCK=\
"server {
	listen 80;
	listen [::]:80;

	root /var/www/html;

	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
	}
}"

bash -c "echo -e '$SERVER_BLOCK' > /etc/nginx/sites-enabled/default"

service nginx restart
